### ISSUE TITLE
doesn't build

### ISSUE THREAD

**Issue by caffeinelucy** [SpexGuy/Zig-Gltf-Display#1]
using either "zig build" "zig build target=x86_64-windows-gnu" because no build info is provided:
```
/usr/lib/zig/0.9.1/lib/std/builtin.zig:13:16:_` error: get this from @import("builtin") instead of std.builtin
pub const os = @compileError("get this from @import(\"builtin\") instead of std.builtin");
```
this is on debian using zig 0.9.1

**Comment by SpexGuy** [comment]
Sorry about that, this project was very out of date 😅
It should be working now with 459ab4f, please reopen this issue or make a new one if you are still having problems.
